logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    dev.pulsermm.gateway: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: Identity
        url: /v3/api-docs/rbac-service
      - name: Endpoints
        url: /v3/api-docs/endpoint-service
      - name: Metrics
        url: /v3/api-docs/metric-service
      - name: Commands
        url: /v3/api-docs/commands-service
      - name: Alerts
        url: /v3/api-docs/alert-service
      - name: Audit
        url: /v3/api-docs/audit-service
      - name: Integrations
        url: /v3/api-docs/integration-service
    urls-primary-name: Identity
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
