version: 2
project_name: pulse-rmm

builds:
  - id: pulse-agent
    main: .
    binary: pulse-agent
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.Version={{ .Version }} -s -w
    targets:
      - linux_amd64
      - windows_amd64

archives:
  - id: default
    name_template: "pulse-agent-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: pulse-packages
    package_name: pulse-agent
    vendor: "mkozakk"
    maintainer: "mkozakk <mkozakk@users.noreply.github.com>"
    homepage: "https://github.com/mkozakk/pulse-rmm"
    description: "Pulse RMM Management Agent"
    license: "MIT"
    bindir: /usr/local/bin
    formats:
      - deb
      - rpm
    contents:
      - src: packaging/pulse-agent-desktop.desktop
        dst: /etc/xdg/autostart/pulse-agent-desktop.desktop
        file_info:
          mode: 0644
      - src: packaging/99-pulse-agent-uinput.rules
        dst: /etc/udev/rules.d/99-pulse-agent-uinput.rules
        file_info:
          mode: 0644
    dependencies:
      - xdg-desktop-portal
    recommends:
      - xdg-desktop-portal-gnome
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-kde
    overrides:
      deb:
        dependencies:
          - ffmpeg
          - xdg-desktop-portal
          - gstreamer1.0-tools
          - gstreamer1.0-plugins-base
          - gstreamer1.0-plugins-good
          - gstreamer1.0-plugins-ugly
          - gstreamer1.0-pipewire
          - gstreamer1.0-libav
          - x11-xserver-utils
      rpm:
        dependencies:
          - ffmpeg-free
          - xdg-desktop-portal
          - gstreamer1-plugins-base
          - gstreamer1-plugins-good
          - gstreamer1-plugins-ugly-free
          - pipewire-gstreamer
          - gstreamer1-libav
          - xorg-x11-server-utils
    scripts:
      postinstall: packaging/scripts/postinstall.sh
      preremove: packaging/scripts/preremove.sh
