global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: pulse-rmm-local

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: pulse-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api-gateway:8080
          - identity-service:8083
          - endpoint-service:8081
          - metric-service:8082
          - commands-service:8084
          - alert-service:8087
          - audit-service:8088
          - integration-service:8091
          - ca-service:8089
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: service
        replacement: '$1'
