package dev.pulsermm.identity.infrastructure;

import dev.pulsermm.identity.domain.User;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.context.ActiveProfiles;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.*;

@Testcontainers
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
class UserRepositoryIT {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine")
        .withDatabaseName("pulse")
        .withUsername("pulse")
        .withPassword("pulse");

    @Autowired
    private UserRepository userRepository;

    @Test
    void flywayMigrationCreatesUsersTable() {
        User user = new User("test_user", "hash");
        User saved = userRepository.saveAndFlush(user);
        assertThat(saved.getId()).isNotNull();
    }

    @Test
    void insertingDuplicateUsernameFailsWithDataIntegrityViolationException() {
        User user1 = new User("admin", "hash1");
        userRepository.save(user1);

        User user2 = new User("admin", "hash2");

        assertThatThrownBy(() -> {
            userRepository.save(user2);
            userRepository.flush();
        }).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void usernameLookupIsCaseSensitive() {
        User user = new User("admin", "hash");
        userRepository.save(user);

        assertThat(userRepository.findByUsername("admin"))
            .as("lowercase 'admin' should be found")
            .isPresent();

        assertThat(userRepository.findByUsername("Admin"))
            .as("mixed-case 'Admin' should not be found")
            .isEmpty();
    }

    @Test
    void createdAtIsPopulatedByDatabase() {
        User user = new User("admin", "hash");
        userRepository.saveAndFlush(user);

        User fetched = userRepository.findByUsername("admin").orElseThrow();
        assertThat(fetched.getCreatedAt())
            .as("createdAt should be populated by database")
            .isNotNull();
    }

    @Test
    void idIsGeneratedByDatabaseViaGenRandomUuid() {
        User user = new User("admin", "hash");

        User saved = userRepository.saveAndFlush(user);

        assertThat(saved.getId())
            .as("id should be generated by database")
            .isNotNull();
    }

    @Test
    void passwordHashColumnAccepts60CharBcryptOutput() {
        String bcryptHash = "a".repeat(60);
        User user = new User("admin", bcryptHash);

        User saved = userRepository.saveAndFlush(user);

        assertThat(saved.getPasswordHash())
            .isEqualTo(bcryptHash);
    }
}
